---

- name: ensure tasks run only on selected os releases
  block:

    - name: enable rpm fusion repositories
      ansible.builtin.package:
        name:
          - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
        state: latest

  when: ansible_distribution == "Fedora"

...
